# Generated by Django 4.2.4 on 2023-08-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_signature_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('signature', precise_bbcode.fields.BBCodeTextField(blank=True, max_length=1024, no_rendered_field=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
