# Generated by Django 4.2.11 on 2024-05-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
