# Generated by Django 4.2.11 on 2024-04-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shout",
            name="_content_rendered",
        ),
        migrations.AlterField(
            model_name="shout",
            name="content",
            field=models.TextField(),
        ),
    ]
