# Generated by Django 4.2.11 on 2024-05-29 19:48

from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("punkweb_bb", "0003_alter_thread_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupStyle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Highest priority is displayed"
                    ),
                ),
                (
                    "_username_style_rendered",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "username_style",
                    precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority",),
            },
        ),
    ]
