# Generated by Django 4.2.4 on 2023-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punkweb_bb', '0003_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='test', max_length=1024),
            preserve_default=False,
        ),
    ]
