# Generated by Django 4.2.4 on 2023-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punkweb_bb', '0004_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
