# Generated by Django 4.2.11 on 2024-05-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0004_groupstyle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={
                "ordering": ("subcategory", "-is_pinned", "-last_post_created_at"),
                "permissions": (
                    ("move_thread", "Can move thread"),
                    ("pin_thread", "Can pin thread"),
                    ("close_thread", "Can close thread"),
                ),
            },
        ),
    ]
