# Generated by Django 4.2.11 on 2024-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0005_alter_thread_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardprofile",
            name="_signature_rendered",
        ),
        migrations.RemoveField(
            model_name="groupstyle",
            name="_username_style_rendered",
        ),
        migrations.RemoveField(
            model_name="post",
            name="_content_rendered",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="_description_rendered",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="_content_rendered",
        ),
        migrations.AlterField(
            model_name="boardprofile",
            name="signature",
            field=models.TextField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupstyle",
            name="username_style",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thread",
            name="content",
            field=models.TextField(),
        ),
    ]
