# Generated by Django 4.2.11 on 2024-06-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0006_remove_boardprofile__signature_rendered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
