# Generated by Django 4.2.4 on 2023-08-22 15:10

from django.db import migrations, models
import punkweb_bb.models


class Migration(migrations.Migration):

    dependencies = [
        ('punkweb_bb', '0006_boardprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=punkweb_bb.models.profile_image_upload_to),
        ),
    ]
