# Generated by Django 4.2.11 on 2024-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punkweb_bb', '0007_boardprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstyle',
            name='username_style',
            field=models.TextField(help_text='BBCode style for the username.  Use {USER} as a placeholder for the username.  Example: [b]{USER}[/b]'),
        ),
    ]
