# Generated by Django 4.2.4 on 2023-08-25 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import precise_bbcode.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('punkweb_bb', '0007_alter_boardprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_content_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
