# Generated by Django 4.2.4 on 2023-09-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punkweb_bb', '0008_shout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_description_rendered',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
