# Generated by Django 4.2.11 on 2024-04-05 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "punkweb_bb",
            "0010_alter_boardprofile_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={
                "ordering": ("subcategory", "-is_pinned", "-last_post_created_at")
            },
        ),
        migrations.AddField(
            model_name="thread",
            name="last_post_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
