# Generated by Django 4.2.11 on 2024-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0011_alter_thread_options_thread_last_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="staff_post_only",
            field=models.BooleanField(default=False),
        ),
    ]
