from django.conf import settings

PUNKWEB_BB = getattr(settings, "PUNKWEB_BB", {})

SITE_NAME = PUNKWEB_BB.get("SITE_NAME", "PUNKWEB")
SITE_TITLE = PUNKWEB_BB.get("SITE_TITLE", "PunkwebBB")
PARSER = PUNKWEB_BB.get("PARSER", "bbcode")
FAVICON = PUNKWEB_BB.get("FAVICON", "punkweb_bb/favicon.ico")
OG_IMAGE = PUNKWEB_BB.get("OG_IMAGE", None)
LOGIN_URL_NAME = PUNKWEB_BB.get("LOGIN_URL_NAME", "login")
SIGNUP_URL_NAME = PUNKWEB_BB.get("SIGNUP_URL_NAME", None)
LOGOUT_URL_NAME = PUNKWEB_BB.get("LOGOUT_URL_NAME", "logout")
SHOUTBOX_ENABLED = PUNKWEB_BB.get("SHOUTBOX_ENABLED", True)
SHOUTBOX_POLLING_ENABLED = PUNKWEB_BB.get("SHOUTBOX_POLLING_ENABLED", True)
SHOUTBOX_POLLING_INTERVAL = PUNKWEB_BB.get("SHOUTBOX_POLLING_INTERVAL", 30)
DISCORD_WIDGET_ENABLED = PUNKWEB_BB.get("DISCORD_WIDGET_ENABLED", False)
DISCORD_WIDGET_THEME = PUNKWEB_BB.get("DISCORD_WIDGET_THEME", "dark")
DISCORD_SERVER_ID = PUNKWEB_BB.get("DISCORD_SERVER_ID", None)
